apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
      #  image: ghcr.io/tcardone/trc/nginx:latest
      #  image: "us-west1-docker.pkg.dev/playground-s-11-b1f9bdab/gcp-repo/nginx:latest"
        image: <IMAGE_NAME>
        env:
        - name: productFetchUrl
          #value: "http://35.227.138.148:8080/"
          value: <PRODUCTFETCHURL>
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      #imagePullSecrets:
      #    - name: dockerconfigjson-github-com